import React from 'react'
import Head from 'next/head'
import FooterPage from '../../components/FooterPage'
import NavPage from '../../components/NavPage'
import Appointment from '../../components/appointment/appointment'

function Cita ({ children, title = 'Checa y Cuadra' }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavPage />
      {children}
      <Appointment />
      <FooterPage />
    </>
  )
}

export default Cita
