import React from 'react'
import Head from 'next/head'
import FooterPage from './FooterPage'
import NavbarPage from './NavbarPage'

function Layout ({ children, title = 'Checa y Cuadra' }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavbarPage />
      {children}
      <FooterPage />
    </>
  )
}

export default Layout
