import { useState, useEffect } from 'react';
import Head from 'next/head'
import FooterPage from '../../../components/FooterPage'
import NavPage from '../../../components/NavPage'
import Appointment from '../../../components/appointment/appointment'
import { useRouter } from "next/router";
import Snackbar from '../../../components/Notifications/SnackbarMercadoPago'
import { URL_FULL } from '../../../services/config'

function Cita ({ children, title = 'Checa y Cuadra' }) {
  
  const router = useRouter()
  const {id} = router.query
  const code = router.query.code
  // console.log("code google", code)
  
  const [accountUser, setAccountUser]=useState({
    name:"",
    lastname:"",
    degree:"",
    degreeId:"",
    profileImage:"",
    description:"",
    role:"",
    evaluation:"",
    specialities:[{
      id:0,
      title:""
    }],
    address:{
      town:"",
      state:""
    },
    Schedule:{
      costHour:"",
    }
  })
  // Fetch de seleccion de card
 
  useEffect(() => {
    if(router.isReady){
      
      const endpoint=`${URL_FULL}/account/${id}`
    
      // console.log(endpoint)
      const optionsAccount = {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json'
        },
      }
      // console.log(endpoint)
      fetch(`${endpoint}`,optionsAccount).then((res) => {
        res.json().then((value) => {
       //   console.log('resultado value', value)
          setAccountUser(value)
          // setUsers(data.payload) // Revisar
        })
      })
    }
  }, [id])

  const {name, lastname, degree,degreeId,profileImage, description, role, evaluation, specialities, address, Schedule,schedules} = accountUser

  // proceso de pago
    async function patchAccount (url) {
      // console.log("entrando a la funcion")
      const options = {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json'
        }
      }
      const response = await fetch(url, options)
      console.log(response)
      return response.json()
    }

    // Enviar el patch de cita con el boton de confirmar cita
    // Aqui se crea el meeting de google
    const statusPayment = router.query.collection_status

    // console.log(">Aqui llega statusPayment")

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavPage />
      {children}
      <Appointment 
      // handlerAuthGoogle = {handlerAuthGoogle}
      id = {id}
      name = {name}
      lastname ={lastname}
      degree = {degree}
      degreeId = {degreeId}
      profileImage = {profileImage}
      description = {description}
      role={role}
      evaluation= {evaluation}
      specialities = {specialities}
      address ={address}
      Schedule = {Schedule}
      times={schedules}
      statusPayment={statusPayment}
      />
        {statusPayment && (<Snackbar statusPayment={statusPayment} /> )}
      <FooterPage />
    </>
  )
}

export default Cita
